data/server_promo/config/routes.rb
Rails.application.routes.draw do
  resources :news
  resources :landmarks
  resources :albums
  resources :photos
  
  
  resources :events
  resources :groups
  resources :tours
  resources :businesses
  resources :pois
  resources :artifacts

root 'inicio#home'
   
    resources :projetos
    
  get 'cadastrar', to: 'users#new'
  resources :users, except: [:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  resources :categories
  
  get 'sobre', to: 'inicio#about'
  get 'informacoes', to: 'inicio#information'

  
end
Rails.application.routes.draw do  
  resources :news
  resources :landmarks
  resources :albums
  resources :photos
  resources :events
  resources :groups
  resources :tours
  resources :businesses
  resources :pois
  resources :users
  mount API::Base, at: "/"
end 

data/server_promo/app/models/album.rb
class Album < ApplicationRecord
    has_many :photos
end

data/server_promo/app/models/artifact.rb
class Artifact < ActiveRecord::Base
    
  before_save :upload_to_s3
  attr_accessor :upload
  belongs_to :projeto
  
  MAX_FILESIZE = 10.megabytes
  validates_presence_of :name, :upload
  validates_uniqueness_of :name
  
  validate :uploaded_fize_size

private
    def upload_to_s3
        s3 = Aws::S3::Resource.new
        user_name = User.name
        obj = s3.bucket(ENV['S3_BUCKET']).object("#{user_name}/#{upload.original_filename}")
        obj.upload_file(upload.path, acl:'public-read')
        self.key = obj.public_url
    end

  def uploaded_fize_size
    if upload 
      errors.add(:upload, "O arquivo não pode ser maior que #{self.class::MAX_FILESIZE}") unless upload.size <= self.class::MAX_FILESIZE
    end
  end
end

data/server_promo/app/models/business.rb
class Business < ApplicationRecord
    belongs_to :pois
end

data/server_promo/app/models/category.rb
class Category < ActiveRecord::Base
    has_many :projeto_categories
    has_many :projetos, through: :projeto_categories
    has_many :poi_categories
    has_many :pois, through: :poi_categories
    validates :name, presence: true, length: { minimum: 3, maximum: 25 }
    validates_uniqueness_of :name
end

data/server_promo/app/models/event.rb
class Event < ApplicationRecord
    has_one_attached :avatar
end

data/server_promo/app/models/group.rb
class Group < ApplicationRecord
    has_many :poi_groups
    has_many :pois, through: :poi_groups

    has_one_attached :avatar
end

data/server_promo/app/models/landmark.rb
class Landmark < ApplicationRecord
    has_many :poi_landmarks
    has_many :pois, through: :poi_landmarks

end

data/server_promo/app/models/news.rb
class News < ApplicationRecord
    has_one_attached :avatar
end

data/server_promo/app/models/photo.rb
class Photo < ApplicationRecord
    belongs_to :album

#    include ImageUploader[:image]
end

data/server_promo/app/models/poi.rb
class Poi < ActiveRecord::Base
    geocoded_by :address
    after_validation :geocode
    has_many :businesses
    has_many :poi_categories
    has_many :categories, through: :poi_categories
    has_many :tour_pois
    has_many :tours, through: :tour_pois
    has_many :poi_groups
    has_many :groups, through: :poi_groups
    has_many :poi_landmarks
    has_many :landmarks, through: :poi_landmarks


    searchkick locations: [:location]
    
    has_one_attached :avatar

    def search_data
        attributes.merge location: { lat: latitude, lon: longitude }    
    end
    
end

data/server_promo/app/models/poi_category.rb
class PoiCategory < ActiveRecord::Base
    belongs_to :poi
    belongs_to :category
end

data/server_promo/app/models/poi_group.rb
class PoiGroup < ActiveRecord::Base
    belongs_to :poi
    belongs_to :group
end

data/server_promo/app/models/poi_landmark.rb
class PoiLandmark < ActiveRecord::Base
    belongs_to :poi
    belongs_to :landmark
end

data/server_promo/app/models/projeto.rb
class Projeto < ActiveRecord::Base
    belongs_to :user
    has_many :projeto_categories
    has_many :categories, through: :projeto_categories
    has_many :projeto_artifacts
    has_many :artifacts, through: :projeto_artifacts
    before_save { self.email = email.downcase }
    validates :nome, presence: true
    validates :especialidade, presence: true
    validates :telefone, presence: true
    validates :endereco, presence: true
    validates :email, presence: true
    validates :user_id, presence: true
end

data/server_promo/app/models/tour.rb
class Tour < ApplicationRecord
    has_many :tour_pois
    has_many :pois, through: :tour_pois
    has_many :user_tours
    has_many :users, through: :user_tours
    has_one_attached :avatar
end

data/server_promo/app/models/tour_poi.rb
class TourPoi < ActiveRecord::Base
    belongs_to :poi
    belongs_to :tour
end

data/server_promo/app/models/user.rb
class User < ActiveRecord::Base
    before_save { self.email = email.downcase }
    has_many :user_tours
    has_many :tours, through: :user_tours

    has_many :projetos, dependent: :destroy
    validates :username, 
        presence: true, 
        uniqueness: { case_sensitive: true }, 
        length: { minumum: 3, maximum: 25 }
        
    VALID_EMAIL_REGEX  =  /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, 
        presence: true, 
        uniqueness: { case_sensitive: true }, 
        length: {  maximum: 105 }, 
        format: { with: VALID_EMAIL_REGEX }
    has_secure_password
end

data/server_promo/app/models/user_tour.rb
class UserTour < ActiveRecord::Base
    belongs_to :user
    belongs_to :tour
end

data/server_promo/app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :description, :date, :start_date, :end_date, :start_time, :end_time, :avatar)
    end
end

data/server_promo/app/helpers/events_helper.rb
module EventsHelper
end

data/server_promo/app/helpers/news_helper.rb
module NewsHelper
end

data/server_promo/app/helpers/pois_helper.rb
module PoisHelper
end

data/server_promo/app/helpers/tours_helper.rb
module ToursHelper
end

data/server_promo/app/views/events/_form.html.erb
<% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="container">
<h1 align="center">Criar Evento</h1>
<%= form_with(model: event, local: true, :html => {class: "form-horizontal", role: "form"}) do |form| %>

 <div class="form-group">
        <div class="control-label col-sm-2">
            <%= form.label "Nome do Evento" %>
        </div>
        <div class="col-sm-8">
            <%= form.text_field :name, id: :event_name, class: "form-control", placeholder: "Nome do Evento", autofocus: true %>
        </div>

    </div>

  <div class="form-group">
        <div class="control-label col-sm-2">
            <%= form.label "Descrção do Evento" %>
        </div>
        <div class="col-sm-8">
            <%= form.text_area :description, id: :event_name, class: "form-control", placeholder: "Descrição do Evento", autofocus: true %>
        </div>

    </div>

<div class="form-group">
        <div class="control-label col-sm-2">
            <%= form.label "Data" %>
        </div>
        <div class="col-sm-8">
            <%= form.date_field :date, id: :event_date, class: "form-control" %>
        </div>

    </div>

<div class="form-group">
        <div class="control-label col-sm-2">
            <%= form.label "Início Dia" %>
        </div>
        <div class="col-sm-8">
            <%= form.date_field :start_date, id: :event_start_date, class: "form-control" %>
        </div>

    </div>

    <div class="form-group">
        <div class="control-label col-sm-2">
            <%= form.label "Término Dia" %>
        </div>
        <div class="col-sm-8">
            <%= form.date_field :end_date, id: :event_end_date, class: "form-control" %>
        </div>

    </div>

<div class="form-group">
        <div class="control-label col-sm-2">
            <%= form.label "Início" %>
        </div>
        <div class="col-sm-8">
            <%= form.time_field :start_time, id: :event_start_time, class: "form-control" %>
        </div>

    </div>

<div class="form-group">
        <div class="control-label col-sm-2">
            <%= form.label "Término" %>
        </div>
        <div class="col-sm-8">
            <%= form.time_field :end_time, id: :event_end_time, class: "form-control" %>
        </div>

    </div>
<div class="form-group">
        <div class="control-label col-sm-2">
    <%= form.label "Imagem" %>
    </div>
<div class="col-sm-8">
    <%= form.file_field :avatar %>
  </div>
</div>

    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <%= form.submit "Salvar", class: 'btn btn-primary btn-lg' %>
        </div>
    </div>

  <% end %>
</div>

data/server_promo/app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

data/server_promo/app/views/events/index.html.erb
<p id="notice"><%= notice %></p>
<main class="content color-event">
  <div class="content-filler-lg">
  </div>

  <header class="content-header">
    <%= image_tag '/images/front_end/icons/pin-event.svg', class: 'content-header-icon' %>
    <h1 class="content-header-title">
      Eventos
    </h1>
  </header>
    <div class="container">

<%= month_calendar events: @events  do |date, events| %>
<%= date.day %>
    <% events.each do |event| %>
      <div class="cal-dia row">
      <%= link_to event_path(event) do %>
      <div class="cal-hora col-xs-3">
        <%= l(event.start_time.to_time, format: :hora)  %>
      </div>
      <div class="col-xs-9 events-list-item-name">
 <% if event.avatar.attached? %><%= image_tag event.avatar.variant(resize: "100x60") %><% else %> https://picsum.photos/100 <% end %>
      </div>
      <div class="col-xs-12">        
              <%= event.name %>
            </div>
         <% end %>
      </div>
    <% end %>
<% end %>

<%= link_to 'Novo Evento', new_event_path %>
</div>

data/server_promo/app/views/events/new.html.erb
<%= render 'form', event: @event %>

<%= link_to 'Voltar', events_path %>

data/server_promo/app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<main class="content color-event">
  <div class="content-filler-lg">
  </div>

  <header class="content-header">
    <%= image_tag '/images/front_end/icons/pin-event.svg', class: 'content-header-icon' %>
    <h1 class="content-header-title">

      <%= @event.name %>
      <div class="content-header-subtitle color-event">
        <%# if @event.start.to_date == @event.ending.to_date %>
          <%= l(@event.start_date, format: :short) %>
        <%# else %>
          <%#= @event.start_time %>
          <%#= @event.end_time %>
        <%# end %>
      </div>
    </h1>
<%= link_to 'Editar', edit_event_path(@event) %> |
<%= link_to 'Voltar', events_path %>

  </header>

  <div class="content-tabs">
    <div class="content-tabs-spacer">
    </div>
    <div class="content-tabs-options">
      <%#= link_to "https://www.facebook.com/sharer/sharer.php?u=#{event_url(@event)}", class: 'content-tabs-options-item', target: '_blank' do %>
        <%#= image_tag '/imgages/front_end/facebook-white.svg', class:'content-tabs-share-icon' %>
      <%# end %>
      <%#= link_to "https://twitter.com/home?status=#{event_url(@event)}", class: 'content-tabs-options-item', target: '_blank' do %>
        <%#= image_tag '/images/front_end/twitter-white.svg', class:'content-tabs-share-icon' %>
      <%# end %>
    </div>
  </div>

  <div class="content-frame">
    <div class="event">
      <article class="event-about">
      <% if @event.avatar.attached? %><%= image_tag @event.avatar.variant(resize: "400x300") %><% else %> https://picsum.photos/200 <% end %>
        <h1>Descrição:<%#= t 'events.show.about_event' %></h1>
        <%#= markdown_to_html @event.description.to_s %><%= @event.description %>
      </article>
      <div class="event-information">
        <%# if @event.registration.active %>
          <div class="event-registration-aside">
            <%# if @event.ended? %>
              <div class="event-registration-closed">
                fechado<%= t :event_closed, scope: 'event/specifics.registration' %>
              </div>
            <%# else %>
              <%# if @event.registration.ended? %>
                <div class="event-registration-closed">
                  periondo<%#= t :period_closed, scope: 'event/specifics.registration' %>
                </div>
              <%# elsif @event.registration.started? %>
                <%#= link_to  t(:registration_for_this_event, scope: 'event/specifics.registration'), event_registrations_path(@event), class: 'event-registration-aside-button' %>
                <div class="grid">
                  <div class="grid-cell span-7 event-registration-aside-quota">
                    <%# if @event.registration.quota.present? %>
                      <%#= pluralize @event.registrations_left, t(:remaining_vacancy, scope: 'event/specifics.registration'), 
                          t(:vacancies_remaining, scope: 'event/specifics.registration') %>
                    <%# end %>
                  </div>
                  <div class="grid-cell span-5 event-registration-aside-regulation">
                    <%# if @event.registration.regulation.present? %>
                      <%#= link_to t(:regulation, scope: 'event/specifics.registration'), @event.registration.regulation %>
                    <%# end %>
                  </div>
                </div>
              <%# else %>
                <div class="event-registration-closed">
                  <%#= t :not_opened, scope: 'event/specifics.registration' %>
                </div>
              <%# end %>
            <%# end %>
          </div>
        <%# end %>

      </div>
    </div>
  </div>
</main>