data/server_promo/config/routes.rb
Rails.application.routes.draw do
  resources :news
  resources :landmarks
  resources :albums
  resources :photos
  
  
  resources :events
  resources :groups
  resources :tours
  resources :businesses
  resources :pois
  resources :artifacts

root 'inicio#home'
   
    resources :projetos
    
  get 'cadastrar', to: 'users#new'
  resources :users, except: [:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  resources :categories
  
  get 'sobre', to: 'inicio#about'
  get 'informacoes', to: 'inicio#information'

  
end
Rails.application.routes.draw do  
  resources :news
  resources :landmarks
  resources :albums
  resources :photos
  resources :events
  resources :groups
  resources :tours
  resources :businesses
  resources :pois
  resources :users
  mount API::Base, at: "/"
end 

data/server_promo/app/models/album.rb
class Album < ApplicationRecord
    has_many :photos
end

data/server_promo/app/models/artifact.rb
class Artifact < ActiveRecord::Base
    
  before_save :upload_to_s3
  attr_accessor :upload
  belongs_to :projeto
  
  MAX_FILESIZE = 10.megabytes
  validates_presence_of :name, :upload
  validates_uniqueness_of :name
  
  validate :uploaded_fize_size

private
    def upload_to_s3
        s3 = Aws::S3::Resource.new
        user_name = User.name
        obj = s3.bucket(ENV['S3_BUCKET']).object("#{user_name}/#{upload.original_filename}")
        obj.upload_file(upload.path, acl:'public-read')
        self.key = obj.public_url
    end

  def uploaded_fize_size
    if upload 
      errors.add(:upload, "O arquivo não pode ser maior que #{self.class::MAX_FILESIZE}") unless upload.size <= self.class::MAX_FILESIZE
    end
  end
end

data/server_promo/app/models/business.rb
class Business < ApplicationRecord
    belongs_to :pois
end

data/server_promo/app/models/category.rb
class Category < ActiveRecord::Base
    has_many :projeto_categories
    has_many :projetos, through: :projeto_categories
    has_many :poi_categories
    has_many :pois, through: :poi_categories
    validates :name, presence: true, length: { minimum: 3, maximum: 25 }
    validates_uniqueness_of :name
end

data/server_promo/app/models/event.rb
class Event < ApplicationRecord
    has_one_attached :avatar
end

data/server_promo/app/models/group.rb
class Group < ApplicationRecord
    has_many :poi_groups
    has_many :pois, through: :poi_groups

    has_one_attached :avatar
end

data/server_promo/app/models/landmark.rb
class Landmark < ApplicationRecord
    has_many :poi_landmarks
    has_many :pois, through: :poi_landmarks

end

data/server_promo/app/models/news.rb
class News < ApplicationRecord
    has_one_attached :avatar
end

data/server_promo/app/models/photo.rb
class Photo < ApplicationRecord
    belongs_to :album

#    include ImageUploader[:image]
end

data/server_promo/app/models/poi.rb
class Poi < ActiveRecord::Base
    geocoded_by :address
    after_validation :geocode
    has_many :businesses
    has_many :poi_categories
    has_many :categories, through: :poi_categories
    has_many :tour_pois
    has_many :tours, through: :tour_pois
    has_many :poi_groups
    has_many :groups, through: :poi_groups
    has_many :poi_landmarks
    has_many :landmarks, through: :poi_landmarks


    searchkick locations: [:location]
    
    has_one_attached :avatar

    def search_data
        attributes.merge location: { lat: latitude, lon: longitude }    
    end
    
end

data/server_promo/app/models/poi_category.rb
class PoiCategory < ActiveRecord::Base
    belongs_to :poi
    belongs_to :category
end

data/server_promo/app/models/poi_group.rb
class PoiGroup < ActiveRecord::Base
    belongs_to :poi
    belongs_to :group
end

data/server_promo/app/models/poi_landmark.rb
class PoiLandmark < ActiveRecord::Base
    belongs_to :poi
    belongs_to :landmark
end

data/server_promo/app/models/projeto.rb
class Projeto < ActiveRecord::Base
    belongs_to :user
    has_many :projeto_categories
    has_many :categories, through: :projeto_categories
    has_many :projeto_artifacts
    has_many :artifacts, through: :projeto_artifacts
    before_save { self.email = email.downcase }
    validates :nome, presence: true
    validates :especialidade, presence: true
    validates :telefone, presence: true
    validates :endereco, presence: true
    validates :email, presence: true
    validates :user_id, presence: true
end

data/server_promo/app/models/tour.rb
class Tour < ApplicationRecord
    has_many :tour_pois
    has_many :pois, through: :tour_pois
    has_many :user_tours
    has_many :users, through: :user_tours
    has_one_attached :avatar
end

data/server_promo/app/models/tour_poi.rb
class TourPoi < ActiveRecord::Base
    belongs_to :poi
    belongs_to :tour
end

data/server_promo/app/models/user.rb
class User < ActiveRecord::Base
    before_save { self.email = email.downcase }
    has_many :user_tours
    has_many :tours, through: :user_tours

    has_many :projetos, dependent: :destroy
    validates :username, 
        presence: true, 
        uniqueness: { case_sensitive: true }, 
        length: { minumum: 3, maximum: 25 }
        
    VALID_EMAIL_REGEX  =  /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, 
        presence: true, 
        uniqueness: { case_sensitive: true }, 
        length: {  maximum: 105 }, 
        format: { with: VALID_EMAIL_REGEX }
    has_secure_password
end

data/server_promo/app/models/user_tour.rb
class UserTour < ActiveRecord::Base
    belongs_to :user
    belongs_to :tour
end

data/server_promo/app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]

  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
    @poi_groups = @group.pois.page(1)
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:name, :description, :avatar, pois_ids:[])
    end
end

data/server_promo/app/helpers/groups_helper.rb
module GroupsHelper
end

data/server_promo/app/helpers/news_helper.rb
module NewsHelper
end

data/server_promo/app/helpers/pois_helper.rb
module PoisHelper
end

data/server_promo/app/helpers/tours_helper.rb
module ToursHelper
end

data/server_promo/app/views/groups/_form.html.erb
  <% if group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


<div class="container">
<h1 align="center">Criar Coleção</h1>
    <%= form_with(model: group, local: true, :html => {class: "form-horizontal", role: "form"}) do |f| %>

    <div class="form-group">
        <div class="control-label col-sm-2">
            <%= f.label :name %>
        </div>
        <div class="col-sm-8">
            <%= f.text_field :name, id: :group_name, class: "form-control", placeholder: "Nome da Coleção", autofocus: true %>
        </div>

    </div>

<div class="form-group">
    <%= f.label :avatar %>
    <%= f.file_field :avatar, class: "form-control" %>
</div>

<div class="form-group">
        <div class="control-label col-sm-2">
            <%= f.label :description %>
        </div>
        <div class="col-sm-8">
            <%= f.text_field :description, id: :group_description, class: "form-control", placeholder: "Descrição da Coleção", autofocus: true %>
        </div>

    </div>

    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <%= f.submit "Salvar", class: 'btn btn-primary btn-lg' %>
        </div>
    </div>
<% end %>

    <div class="col-xs-4 col-xs-offset-4">
</div>
</div>

data/server_promo/app/views/groups/_group.html.erb
<span class="badge"><%= link_to group.name, group_path(group) %>  </span>

data/server_promo/app/views/groups/_groups_cards.html.erb
<section class="row">
   

<% Group.all.each do |group| %>

  <div class="col-sm-6 col-md-4">
<%= link_to group_path(group), class: 'place-collection' do %>
  <%= image_tag group.avatar, class: 'place-collection-image' %>
  <span class="place-collection-legend">Coleção</span>
  <span class="place-collection-name"><%= group.name %></span>
<% end %>

</div>   
<% end %> 

</section>

data/server_promo/app/views/groups/_groups_side_menu.html.erb
 <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingOne">
      <h4 class="panel-title">
        <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
        Mais Coleções  
        </a>
      </h4>
    </div>
    <div id="collapseOne" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">
      <div class="panel-body">
      <ul>
     <% Group.all.each do |group| %>
                    <li role="presentation" class="groups_side_menu">
                        <%= link_to "#{group.name}", group_path(group) %>
                        <span class="label label-default"><%= group.pois.count %></span>
                    </li>
    <% end %>
       </ul>
      </div>
    </div>
  </div>

    </div>

data/server_promo/app/views/groups/edit.html.erb
<h1>Editing Group</h1>

<%= render 'form', group: @group %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

data/server_promo/app/views/groups/index.html.erb
<p id="notice"><%= notice %></p>
<main class="content color-place">
    <div class="content-filler-lg"></div>


  <header class="content-header">
    <%= image_tag '/images/front_end/icons/pin-place.svg', class: 'content-header-icon' %>
    <h1 class="content-header-title">Coleções</h1>
  </header>


<section class="container row">
   

<% @groups.each do |group| %>

  <div class="col-sm-6 col-md-4">
<%= link_to group_path(group), class: 'place-collection' do %>
  <%= image_tag group.avatar, class: 'place-collection-image' %>
  <span class="place-collection-legend">Coleção</span>
  <span class="place-collection-name"><%= group.name %></span>
 <%#= link_to 'Destroy', group, method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>

</div>   
<% end %> 

</section>
</main>

data/server_promo/app/views/groups/new.html.erb
<%= render 'form', group: @group %>

<%#= link_to 'Voltar', groups_path %>

data/server_promo/app/views/groups/show.html.erb
<p id="notice"><%= notice %></p>


<main class="content color-place">
  <%= content_tag :div, id: "map", data: { pois: @poi_groups.to_json(methods: [:address]) } do -%>
  <% end -%>
    <div class="content-filler-sm"></div>


  <header class="content-header">
    <%= image_tag '/images/front_end/icons/pin-place.svg', class: 'content-header-icon' %>
    <h1 class="content-header-title">  <%= @group.name %>
</h1>
  </header>
 <div class="content-frame">

  <section class="container row">
    <div  class="col-md-12">
      <%= form_tag(pois_path, :method => "get", id: "search-form", class:"form-inline row") do %>
        <%= text_field_tag :q, params[:q], placeholder: "Buscar Lugares", class:"form-control col-md-10 busca-poi" %>
      <%= submit_tag "Buscar", :q=> nil,  class:"btn btn-primary col-md-2" %>
      <% end %>
    </div>
    
    <div  class="">
       <%#= link_to 'Criar Estabelecimento', new_poi_path, class:"btn btn-success" %>
       <%#= link_to 'Refazer a busca', "", id: "redo-search", class:"btn btn-warning" %>
  
    </div>
    
    </section>
    <br>
     <div class="place"> 
      <div class="row" style="display: contents;">
          <div class="group-detail-main-info col-md-9" style="display: flex; flex-wrap: wrap">
            <%= render 'pois/poicard', obj: @poi_groups %>
          </div>
          <div class="links-sidebar col-md-3">
            <%= render "groups/groups_side_menu" %>
          </div>
      </div>
    </div>
    <%= link_to 'Editar', edit_group_path(@group) %> |
    <%= link_to 'Voltar', groups_path %>
  </div>
</main>