data/server_promo/config/routes.rb
Rails.application.routes.draw do
  resources :news
  resources :landmarks
  resources :albums
  resources :photos
  
  
  resources :events
  resources :groups
  resources :tours
  resources :businesses
  resources :pois
  resources :artifacts

root 'inicio#home'
   
    resources :projetos
    
  get 'cadastrar', to: 'users#new'
  resources :users, except: [:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  resources :categories
  
  get 'sobre', to: 'inicio#about'
  get 'informacoes', to: 'inicio#information'

  
end
Rails.application.routes.draw do  
  resources :news
  resources :landmarks
  resources :albums
  resources :photos
  resources :events
  resources :groups
  resources :tours
  resources :businesses
  resources :pois
  resources :users
  mount API::Base, at: "/"
end 

data/server_promo/app/models/poi.rb
class Poi < ActiveRecord::Base
    geocoded_by :address
    after_validation :geocode
    has_many :businesses
    has_many :poi_categories
    has_many :categories, through: :poi_categories
    has_many :tour_pois
    has_many :tours, through: :tour_pois
    has_many :poi_groups
    has_many :groups, through: :poi_groups
    has_many :poi_landmarks
    has_many :landmarks, through: :poi_landmarks


    searchkick locations: [:location]
    
    has_one_attached :avatar

    def search_data
        attributes.merge location: { lat: latitude, lon: longitude }    
    end
    
end

data/server_promo/app/controllers/pois_controller.rb
class PoisController < ApplicationController
  before_action :set_poi, only: [:show, :edit, :update, :destroy]

  # GET /pois
  # GET /pois.json
  def index
    @pois = if params[:l]
      sw_lat, sw_lng, ne_lat, ne_lng = params[:l].split(",")
      Poi.search("*", page: params[:page], per_page: 4, where: {
        location: {
          top_left: {
            lat: ne_lat,
            lon: sw_lng
          },
          bottom_right: {
            lat: sw_lat,
            lon: ne_lng
          }
        }
      })
    elsif params[:q]
      location = Geocoder.search(params[:q]).first
      Poi.search(
        params.fetch(:q, "*"), 
        fields: [:name, :string, :address, :near, :categories],
        page: params[:page], per_page: 4
 

         # @pois = Poi.search(params[:q]), fields: [:name], page: params[:page], per_page = 1
     
        # boost_by_distance: {location: {origin: {lat: location.latitude, lon: location.longitude}}},
        # where: {
        #   location: {
        #     near: {
        #       lat: location.latitude,
        #       lon: location.longitude
        #     },
        #     within: "5mi"
        #   }
        # }
        )
    # elsif params[:near]
    #   #Transaction.near(params[:near]).page(params[:page]).per(5)
    #   location = Geocoder.search(params[:near]).first
    #   Poi.search "*", page: params[:page], per_page: 2,
    #     boost_by_distance: {location: {origin: {lat: location.latitude, lon: location.longitude}}},
    #     where: {
    #       location: {
    #         near: {
    #           lat: location.latitude,
    #           lon: location.longitude
    #         },
    #         within: "5mi"
    #       }
    #     }
    else
      Poi.all.page(params[:page]).per(8)
    end
  end

  # GET /pois/1
  # GET /pois/1.json
  def show
  end

  # GET /pois/new
  def new
    @poi = Poi.new
  end

  # GET /pois/1/edit
  def edit
  end

  # POST /pois
  # POST /pois.json
  def create
    @poi = Poi.new(poi_params)
    respond_to do |format|
      if @poi.save
        format.html { redirect_to @poi, notice: 'Poi was successfully created.' }
        format.json { render :show, status: :created, location: @poi }
      else
        format.html { render :new }
        format.json { render json: @poi.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pois/1
  # PATCH/PUT /pois/1.json
  def update
    respond_to do |format|
      if @poi.update(poi_params)
        format.html { redirect_to @poi, notice: 'Poi was successfully updated.' }
        format.json { render :show, status: :ok, location: @poi }
      else
        format.html { render :edit }
        format.json { render json: @poi.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pois/1
  # DELETE /pois/1.json
  def destroy
    @poi.destroy
    respond_to do |format|
      format.html { redirect_to pois_url, notice: 'Poi was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_poi
      @poi = Poi.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def poi_params
      params.require(:poi).permit(:name, :string, :onCallout, :address, :latitude, :longitude, :avatar, category_ids:[], tour_ids:[], group_ids:[], landmark_ids:[])
    end
end

data/server_promo/app/helpers/pois_helper.rb
module PoisHelper
end

data/server_promo/app/views/pois/_form.html.erb
<%= form_for(@poi) do |f| %>
  <% if @poi.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@poi.errors.count, "error") %> prohibited this poi from being saved:</h2>

      <ul>
      <% @poi.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
<div class="form-group">
    <%= f.label :avatar %>
    <%= f.file_field :avatar, class: "form-control" %>
</div>

  <div class="field">
    <%= f.label :string %><br>
    <%= f.text_field :string %>
  </div>

  <div class="field">
    <%= f.label :acessibilidade %><br>
    <%= f.text_field :acessibilidade %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
   <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </div>
<%#= f.select :category_ids[], options_from_collection_for_select(Category.all, :id, :name), include_blank: true %>

  <p>
    <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
    <% cb.label(class: "checkbox-inline input_checkbox") {cb.check_box(class: "checkbox") + cb.text} %>
    <% end %>
  </p>

  <p>
    <%= f.collection_check_boxes :tour_ids, Tour.all, :id, :name do |cb| %>
    <% cb.label(class: "checkbox-inline input_checkbox") {cb.check_box(class: "checkbox") + cb.text} %>
    <% end %>
  </p>

  <p>
    <%= f.collection_check_boxes :group_ids, Group.all, :id, :name do |cb| %>
    <% cb.label(class: "checkbox-inline input_checkbox") {cb.check_box(class: "checkbox") + cb.text} %>
    <% end %>
  </p>

<p>
    <%= f.collection_check_boxes :landmark_ids, Landmark.all, :id, :title do |cb| %>
    <% cb.label(class: "checkbox-inline input_checkbox") {cb.check_box(class: "checkbox") + cb.text} %>
    <% end %>
  </p>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

data/server_promo/app/views/pois/_map_home.html.erb
<style>
  .map-cards-wrapper {
  display: flex;
  flex-wrap: wrap;
  justify-content: space-between;
  }
</style>

<div class="map map-search">
      <%= form_tag(pois_path, :method => "get", id: "search-form", class:"map-search-form") do %>
        <%= text_field_tag :q, params[:q], placeholder: "Buscar Lugares", class:"map-search-form-field busca-poi" %>
      <%= submit_tag "Buscar", :q=> nil,  class:"map-search-form-button" %>
      <% end %>
</div>

 <%= content_tag :div, class: "map-container", id: "map", data: { pois: @map_pois.to_json(methods: [:address]) } do -%>
  <% end -%>
<div class="container">
<div class="map-cards-wrapper">
      <a href="<%= path_to_prev_page @map_pois %>" >
        <div class="map-carousel-control-previous">
          <%= image_tag '/images/front_end/icons/chevron-left-white.svg', class: 'map-carousel-control-previous-chevron' %>
        </div>
        </a>
        <% @map_pois.each do |poi| %>


<div class="map-carouseĺ-item">
  <%= link_to poi_path(poi), class: 'place-card' do %>
  <div class="place-card-image" style="background-image:url(<%= url_for(poi.avatar) %>)" >&nbsp;</div>
    <div class="place-card-name"><%= poi.name %></div>
    <div class="place-card-address"><%= poi.address %></div>
    <%# if place.schedule.any? %>
      <%# if place.open? %>
        <div class="place-card-status-open">
          <%= image_tag '/images/front_end/icons/open.svg', class: 'place-card-status-icon' %>
          Aberto
        </div>
      <%# else %>
        <!-- <div class="place-card-status-closed"> -->
          <%#= image_tag '/images/front_end/icons/closed-gray.svg', class: 'place-card-status-icon' %>
        <!--  Fechado
        </div> -->
      <%# end %>
  <% end %>

  </div>
<% end %>
      <a href="<%= path_to_next_page @map_pois %>" >
        <div class="map-carousel-control-next" data-carousel-control-next>
          <%= image_tag '/images/front_end/icons/chevron-right-white.svg', class: 'map-carousel-control-next-chevron' %>
        </div>
      </a>
</div>
</div>

data/server_promo/app/views/pois/_place.html.erb
<%= content_tag :tr, 'data-href' => edit_place_path(place) do %>
  <td>
    <div class="truncate">
      <%= place.name %>
    </div>
    <div class="truncate small quiet">
      <% if place.physical? %>
        <%= place.address.formatted %>
      <% else %>
        Não possui endereço físico
      <% end %>
    </div>
  </td>
  <td>
    <% if place.categories.present? %>
      <small><%= formatted_place_categories(place) %></small>
    <% else %>
      -
    <% end %>
  </td>
  <td>
    <%= time_tag place.updated_at, title: l(place.updated_at) do %>
      <%= t 'datetime.time_ago', time: time_ago_in_words(place.updated_at) %>
    <% end %>
  </td>
  <td>
    <% if place.active %>
      <span class="positive">Ativo</span>
    <% else %>
      <span class="negative">Inativo</span>
    <% end %>
  </td>
<% end %>

data/server_promo/app/views/pois/_poi.html.erb
<% if controller_name == 'inicio' && action_name == 'home' %>
                  <!--   <img src="<%= url_for(poi.avatar) %>" alt="..."> -->
                  <%= image_tag poi.avatar.variant(resize: "1200x460") %>
            <%= link_to poi_path(poi) do %>
      <div class="container">
            <div class="carousel-item-caption">
              <span class="carousel-item-caption-tag color-place">PONTO TURÍSTICO</span>
              <p>     <%= poi.name %>
          </p>
            </div>
          </div>
            <% end %>
  
       
<% else %>
    <div class="grid-cell span-12 skip-2-from-1">
        <%= link_to poi_path(poi) do %>
        <div class="landmark-card", style="background-image: url(<%=url_for(poi.avatar)%>)" >
          <span class="landmark-card-name"><%= poi.name %></span>
          </div>
        <% end %>
     </div>

<% end  %>

data/server_promo/app/views/pois/_poicard.html.erb
<% obj.each do |poi| %>

<div class="place-grid-item">
  <%= link_to poi_path(poi), class: 'place-card' do %>
  <div class="place-card-image" style="background-image:url(<% if poi.avatar.attached? %> <%= url_for(poi.avatar) %> <% else %> https://picsum.photos/200 <% end %>)" >&nbsp;</div>
    <div class="place-card-name"><%= poi.name %></div>
    <div class="place-card-address"><%= poi.address %></div>
    <%# if place.schedule.any? %>
      <%# if place.open? %>
        <div class="place-card-status-open">
          <%= image_tag '/images/front_end/icons/open.svg', class: 'place-card-status-icon' %>
          Aberto
        </div>
      <%# else %>
        <!-- <div class="place-card-status-closed"> -->
          <%#= image_tag '/images/front_end/icons/closed-gray.svg', class: 'place-card-status-icon' %>
        <!--  Fechado
        </div> -->
      <%# end %>
              <% end %>
               <% if poi.categories.any? %>
               <p class="category-wrapper">Categorias: <%= render poi.categories %></p>
    <%# else %>
      <div class="place-card-no-status">&nbsp;</div>
       <%# end %>
  <% end %>
                  <% if logged_in? %>
             <p>
               <%= link_to 'Detalhes', poi, class:"btn btn-default btn-xs" %>
               <%= link_to 'Editar', edit_poi_path(poi), class:"btn btn-default btn-xs" %>
               <%= link_to 'Deletar', poi, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-default btn-xs" %>
             </p>
          <% end %>
  </div>


<% end %>

data/server_promo/app/views/pois/_poisinner.html.erb
  <%= link_to poi_path(poi), class: 'landmark-card', style: "background-image:url(<%= url_for(poi.avatar) %>)" do %>
    <span class="landmark-card-name"><%= poi.name %></span>
  <% end %>

data/server_promo/app/views/pois/edit.html.erb
<h1>Editing Poi</h1>

<%= render 'form' %>

<%= link_to 'Show', @poi %> |
<%= link_to 'Back', pois_path %>

data/server_promo/app/views/pois/index.html.erb
<p id="notice"><%= notice %></p>


<main class="content color-place">
  <%= content_tag :div, id: "map", data: { pois: @pois.to_json(methods: [:address]) } do -%>
  <% end -%>
    <!--<div class="content-filler-sm"></div> -->


  <header class="content-header">
    <%= image_tag '/images/front_end/icons/pin-place.svg', class: 'content-header-icon' %>
    <h1 class="content-header-title">Conheça Campinas</h1>
  </header>
<div class="content-frame">

  <section class="container row">
    <div  class="col-md-12">
      <%= form_tag(pois_path, :method => "get", id: "search-form", class:"form-inline row") do %>
        <%= text_field_tag :q, params[:q], placeholder: "Buscar Lugares", class:"form-control col-md-10 busca-poi" %>
      <%= submit_tag "Buscar", :q=> nil,  class:"btn btn-primary col-md-2" %>
      <% end %>
    </div>
    
    <div  class="">
       <%#= link_to 'Criar Estabelecimento', new_poi_path, class:"btn btn-success" %>
       <%#= link_to 'Refazer a busca', "", id: "redo-search", class:"btn btn-warning" %>
  
    </div>
    
    </section>
    <br>

      <div class="place">
        <% @pois.each do |poi| %>


<div class="place-grid-item">
  <%= link_to poi_path(poi), class: 'place-card' do %>
  <div class="place-card-image" style="background-image:url(<% if poi.avatar.attached? %> <%= url_for(poi.avatar) %> <% else %> https://picsum.photos/200 <% end %>)" >&nbsp;</div>
    <div class="place-card-name"><%= poi.name %></div>
    <div class="place-card-address"><%= poi.address %></div>
    <%# if place.schedule.any? %>
      <%# if place.open? %>
        <div class="place-card-status-open">
          <%= image_tag '/images/front_end/icons/open.svg', class: 'place-card-status-icon' %>
          Aberto
        </div>
      <%# else %>
        <!-- <div class="place-card-status-closed"> -->
          <%#= image_tag '/images/front_end/icons/closed-gray.svg', class: 'place-card-status-icon' %>
        <!--  Fechado
        </div> -->
      <%# end %>
              <% end %>
               <% if poi.categories.any? %>
               <p>Categorias: <%= render poi.categories %></p>
    <%# else %>
      <div class="place-card-no-status">&nbsp;</div>
       <%# end %>
  <% end %>
                  <% if logged_in? %>
             <p>
               <%= link_to 'Detalhes', poi, class:"btn btn-default btn-xs" %>
               <%= link_to 'Editar', edit_poi_path(poi), class:"btn btn-default btn-xs" %>
               <%= link_to 'Deletar', poi, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-default btn-xs" %>
             </p>
          <% end %>
  </div>


<% end %>
</div>

     <div class="paginacao col-xs-12">
     <%= paginate @pois %>
   </div>
 </div>
 
</div> 
  </div> 
</div> 


</main>
</div> 

data/server_promo/app/views/pois/new.html.erb
<h1>New Poi</h1>

<%= render 'form' %>

<%= link_to 'Back', pois_path %>

data/server_promo/app/views/pois/show.html.erb
<style>
#mapin {
  height: 400px
}
</style>
<p id="notice"><%= notice %></p>
<main class="content color-place">
  <%= content_tag :div, id: "mapin" do -%>
  <% end -%>
  <!-- <div class="content-filler-sm"></div> -->
  <header class="content-header">
    <%= image_tag '/images/front_end/icons/pin-place.svg', class: 'content-header-icon' %>
    <h1 class="content-header-title">  <%= @poi.name %></h1>
  </header>
  <section class="container row">
    <div  class="col-md-6">
      <%= form_tag(pois_path, :method => "get", id: "search-form", class:"form-inline row") do %>
        <%= text_field_tag :q, params[:q], placeholder: "Buscar Lugares", class:"form-control col-md-10 busca-poi" %>
        <%= submit_tag "Buscar", :q=> nil,  class:"btn btn-primary col-md-2" %>
      <% end %>
    </div>
    <div  class="col-md-6">
      <%#= link_to 'Criar Estabelecimento', new_poi_path, class:"btn btn-success" %>
      <%#= link_to 'Refazer a busca', "", id: "redo-search", class:"btn btn-warning" %>
    </div>
  </section>
  <br>
  <div class="content-frame">
    <div class="place">
      <div class="row">
        <div class="poi-detail-main-info col-md-9">
          <img class="poi-detail-main-photo" src="<%= url_for(@poi.avatar) %>" alt="...">
          <br>
          <p>
            <strong>Acessibilidade:</strong>
            <%= @poi.acessibilidade %>
          </p>
          <p>
            <strong>Endereço:</strong>
            <%= @poi.address %>
          </p>
          <% if @poi.categories.any? %>
            <p>Categorias: <%= render @poi.categories %></p>
          <% end %>
          <% if @poi.tours.any? %>
            <p>Roteiros: <%= render @poi.tours %></p>
          <% end %>
          <% if @poi.groups.any? %>
            <p>Coleções: <%= render @poi.groups %></p>
          <% end %>
                 <% if @poi.landmarks.any? %>
            <p>Landmark: <%= render @poi.landmarks %></p>
          <% end %>
          <%= link_to 'Edit', edit_poi_path(@poi) %> |
          <%= link_to 'Back', pois_path %>
        </div>
    <div class="links-sidebar col-md-3">
      <%= render "categories/categories_side_menu" %>
 <%= render "groups/groups_side_menu" %>

    </div>
  </div>
  </div>
  </div>
</main>
<script>
   var map = new GMaps({
        div: '#mapin',
        lat: <%= @poi.latitude %>,	
        lng: <%= @poi.longitude %>
    });
    map.addMarker({
        lat:    <%= @poi.latitude %>,	
        lng: <%= @poi.longitude %>,
  title: '<%= @poi.name %>',
  infoWindow: { 
            content: `<p><%= @poi.name %>
            <h3><%= @poi.string %></h3>
            <a href='/pois/<%=@poi.id %>'><%= @poi.address %></a>
            </p>`
        },
});

</script>