data/server_promo/config/routes.rb
Rails.application.routes.draw do
  resources :news
  resources :landmarks
  resources :albums
  resources :photos
  
  
  resources :events
  resources :groups
  resources :tours
  resources :businesses
  resources :pois
  resources :artifacts

root 'inicio#home'
   
    resources :projetos
    
  get 'cadastrar', to: 'users#new'
  resources :users, except: [:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  resources :categories
  
  get 'sobre', to: 'inicio#about'
  get 'informacoes', to: 'inicio#information'

  
end
Rails.application.routes.draw do  
  resources :news
  resources :landmarks
  resources :albums
  resources :photos
  resources :events
  resources :groups
  resources :tours
  resources :businesses
  resources :pois
  resources :users
  mount API::Base, at: "/"
end 

data/server_promo/app/models/album.rb
class Album < ApplicationRecord
    has_many :photos
end

data/server_promo/app/models/artifact.rb
class Artifact < ActiveRecord::Base
    
  before_save :upload_to_s3
  attr_accessor :upload
  belongs_to :projeto
  
  MAX_FILESIZE = 10.megabytes
  validates_presence_of :name, :upload
  validates_uniqueness_of :name
  
  validate :uploaded_fize_size

private
    def upload_to_s3
        s3 = Aws::S3::Resource.new
        user_name = User.name
        obj = s3.bucket(ENV['S3_BUCKET']).object("#{user_name}/#{upload.original_filename}")
        obj.upload_file(upload.path, acl:'public-read')
        self.key = obj.public_url
    end

  def uploaded_fize_size
    if upload 
      errors.add(:upload, "O arquivo não pode ser maior que #{self.class::MAX_FILESIZE}") unless upload.size <= self.class::MAX_FILESIZE
    end
  end
end

data/server_promo/app/models/business.rb
class Business < ApplicationRecord
    belongs_to :pois
end

data/server_promo/app/models/category.rb
class Category < ActiveRecord::Base
    has_many :projeto_categories
    has_many :projetos, through: :projeto_categories
    has_many :poi_categories
    has_many :pois, through: :poi_categories
    validates :name, presence: true, length: { minimum: 3, maximum: 25 }
    validates_uniqueness_of :name
end

data/server_promo/app/models/event.rb
class Event < ApplicationRecord
    has_one_attached :avatar
end

data/server_promo/app/models/group.rb
class Group < ApplicationRecord
    has_many :poi_groups
    has_many :pois, through: :poi_groups

    has_one_attached :avatar
end

data/server_promo/app/models/landmark.rb
class Landmark < ApplicationRecord
    has_many :poi_landmarks
    has_many :pois, through: :poi_landmarks

end

data/server_promo/app/models/news.rb
class News < ApplicationRecord
    has_one_attached :avatar
end

data/server_promo/app/models/photo.rb
class Photo < ApplicationRecord
    belongs_to :album

#    include ImageUploader[:image]
end

data/server_promo/app/models/poi.rb
class Poi < ActiveRecord::Base
    geocoded_by :address
    after_validation :geocode
    has_many :businesses
    has_many :poi_categories
    has_many :categories, through: :poi_categories
    has_many :tour_pois
    has_many :tours, through: :tour_pois
    has_many :poi_groups
    has_many :groups, through: :poi_groups
    has_many :poi_landmarks
    has_many :landmarks, through: :poi_landmarks


    searchkick locations: [:location]
    
    has_one_attached :avatar

    def search_data
        attributes.merge location: { lat: latitude, lon: longitude }    
    end
    
end

data/server_promo/app/models/poi_category.rb
class PoiCategory < ActiveRecord::Base
    belongs_to :poi
    belongs_to :category
end

data/server_promo/app/models/poi_group.rb
class PoiGroup < ActiveRecord::Base
    belongs_to :poi
    belongs_to :group
end

data/server_promo/app/models/poi_landmark.rb
class PoiLandmark < ActiveRecord::Base
    belongs_to :poi
    belongs_to :landmark
end

data/server_promo/app/models/projeto.rb
class Projeto < ActiveRecord::Base
    belongs_to :user
    has_many :projeto_categories
    has_many :categories, through: :projeto_categories
    has_many :projeto_artifacts
    has_many :artifacts, through: :projeto_artifacts
    before_save { self.email = email.downcase }
    validates :nome, presence: true
    validates :especialidade, presence: true
    validates :telefone, presence: true
    validates :endereco, presence: true
    validates :email, presence: true
    validates :user_id, presence: true
end

data/server_promo/app/models/tour.rb
class Tour < ApplicationRecord
    has_many :tour_pois
    has_many :pois, through: :tour_pois
    has_many :user_tours
    has_many :users, through: :user_tours
    has_one_attached :avatar
end

data/server_promo/app/models/tour_poi.rb
class TourPoi < ActiveRecord::Base
    belongs_to :poi
    belongs_to :tour
end

data/server_promo/app/models/user.rb
class User < ActiveRecord::Base
    before_save { self.email = email.downcase }
    has_many :user_tours
    has_many :tours, through: :user_tours

    has_many :projetos, dependent: :destroy
    validates :username, 
        presence: true, 
        uniqueness: { case_sensitive: true }, 
        length: { minumum: 3, maximum: 25 }
        
    VALID_EMAIL_REGEX  =  /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, 
        presence: true, 
        uniqueness: { case_sensitive: true }, 
        length: {  maximum: 105 }, 
        format: { with: VALID_EMAIL_REGEX }
    has_secure_password
end

data/server_promo/app/models/user_tour.rb
class UserTour < ActiveRecord::Base
    belongs_to :user
    belongs_to :tour
end

data/server_promo/app/controllers/tours_controller.rb
class ToursController < ApplicationController
  before_action :set_tour, only: [:show, :edit, :update, :destroy]

  # GET /tours
  # GET /tours.json
  def index
    @tours = Tour.all
  end

  # GET /tours/1
  # GET /tours/1.json
  def show
    @tour_poi = @tour.pois.last
  end

  # GET /tours/new
  def new
    @tour = Tour.new
  end

  # GET /tours/1/edit
  def edit
  end

  # POST /tours
  # POST /tours.json
  def create
    @tour = Tour.new(tour_params)

    respond_to do |format|
      if @tour.save
        format.html { redirect_to @tour, notice: 'Tour was successfully created.' }
        format.json { render :show, status: :created, location: @tour }
      else
        format.html { render :new }
        format.json { render json: @tour.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tours/1
  # PATCH/PUT /tours/1.json
  def update
    respond_to do |format|
      if @tour.update(tour_params)
        format.html { redirect_to @tour, notice: 'Tour was successfully updated.' }
        format.json { render :show, status: :ok, location: @tour }
      else
        format.html { render :edit }
        format.json { render json: @tour.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tours/1
  # DELETE /tours/1.json
  def destroy
    @tour.destroy
    respond_to do |format|
      format.html { redirect_to tours_url, notice: 'Tour was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tour
      @tour = Tour.find(params[:id])
    end
    def set_user
      @user = User.find(params[:user_id])
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def tour_params
      params.require(:tour).permit(:name, :description, :avatar, :duration, :distance, :audience, :intensity, :details, :latitude, pois_ids:[], users_ids:[])
    end
end

data/server_promo/app/helpers/albums_helper.rb
module AlbumsHelper
end

data/server_promo/app/helpers/news_helper.rb
module NewsHelper
end

data/server_promo/app/helpers/pois_helper.rb
module PoisHelper
end

data/server_promo/app/helpers/tours_helper.rb
module ToursHelper
end

data/server_promo/app/views/tours/_form.html.erb
<%= form_with(model: tour, local: true, :html => {class: "form-horizontal", role: "form"})  do |form| %>
  <% if tour.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tour.errors.count, "error") %> prohibited this tour from being saved:</h2>

      <ul>
      <% tour.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="container">
<h1 align="center">Novo Roteiro</h1>
<div class="form-group">
        <div class="control-label col-sm-2">
            <%= form.label :name %>
        </div>
        <div class="col-sm-8">
            <%= form.text_field :name, id: :group_name, class: "form-control", placeholder: "Nome da Coleção", autofocus: true %>
        </div>

    </div>
<div class="form-group">
    <div class="control-label col-sm-2">
    <%= form.label :avatar %>
</div>
   <div class="col-sm-8">
    <%= form.file_field :avatar, class: "form-control" %>
    </div>
</div>
<div class="form-group">
        <div class="control-label col-sm-2">
            <%= form.label "Público-Alvo" %>
        </div>
        <div class="col-sm-8">
            <%= form.text_field :audience, id: :group_audience, class: "form-control", placeholder: "Público-Alvo", autofocus: true %>
        </div>

    </div>
<div class="form-group">
        <div class="control-label col-sm-2">
            <%= form.label "Duração" %>
        </div>
        <div class="col-sm-8">
            <%= form.text_field :duration, id: :group_duration, class: "form-control", placeholder: "Duração do Roteiro", autofocus: true %>
        </div>

    </div>
<div class="form-group">
        <div class="control-label col-sm-2">
            <%= form.label "Distância" %>
        </div>
        <div class="col-sm-8">
            <%= form.text_field :distance, id: :group_distancia, class: "form-control", placeholder: "Distância do Roteiro", autofocus: true %>
        </div>

    </div>
<div class="form-group">
        <div class="control-label col-sm-2">
            <%= form.label "Intensidade" %>
        </div>
        <div class="col-sm-8">
            <%= form.text_field :intensity, id: :group_intesidade, class: "form-control", placeholder: "Intesidade do Roteiro", autofocus: true %>
        </div>

    </div>

 <div class="form-group">
        <div class="control-label col-sm-2">
            <%= form.label "Descrição" %>
        </div>
        <div class="col-sm-8">
            <%= form.text_field :description, id: :group_description, class: "form-control", placeholder: "Descrição da Coleção", autofocus: true %>
        </div>

    </div>
<div class="form-group">
        <div class="control-label col-sm-2">
            <%= form.label "Detalhes" %>
        </div>
        <div class="col-sm-8">
            <%= form.hidden_field :details, id: :tour_details %>
        <trix-editor input="tour_details"></trix-editor>

        </div>
    

    </div>
  <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <%= form.submit "Salvar", class: 'btn btn-primary btn-lg' %>
        </div>
    </div>
<% end %>
</div>

data/server_promo/app/views/tours/_home_tour_card.html.erb
   <% Tour.all.each do |tour| %>
    <div class="grid-cell span-4 skip-4-from-3">
  <%= link_to tour_path(tour), class: 'tour-card' do %>
    <div class="tour-card-image">
    <img src="<%= url_for(tour.avatar) %>" />
      <%#= image_tag tour_image_url(tour), alt: tour.name %>
    </div>
    <div class="tour-card-name"><%= tour.name %></div>
    <div class="tour-card-description">
      <% if tour.duration.present? %>
      <strong>Duração:</strong><%= tour.duration %>
        <%#= t 'tours.card_duration.html', value: distance_of_time_in_words(tour.duration) %>
        <br>
      <% end %>
      <% if tour.distance.present? %>
      <strong>Distância:</strong> <%= tour.distance %> Km
        <%#= t 'tours.card_distance.html', value: number_to_human(tour.distance) %>
      <% end %>
      <% end %>
      <% if logged_in? %>
         <td><%= link_to 'Detalhes', tour %></td>
        <td><%= link_to 'Editar', edit_tour_path(tour) %></td>
        <td><%= link_to 'Deletar', tour, method: :delete, data: { confirm: 'Você tem certeza?' } %></td>
        <% end %>
    </div>
</div>
  <% end %>

data/server_promo/app/views/tours/_tour.html.erb
<% obj.each do |tour| %>
    <h4 class="media-heading"><%= tour.name %></h4>
<% end %>

data/server_promo/app/views/tours/_tour_card.html.erb
   <% @tours.each do |tour| %>
    <div class="grid-cell span-4 skip-4-from-3">
  <%= link_to tour_path(tour), class: 'tour-card' do %>
    <div class="tour-card-image">
    <img src="<%= url_for(tour.avatar) %>" />
      <%#= image_tag tour_image_url(tour), alt: tour.name %>
    </div>
    <div class="tour-card-name"><%= tour.name %></div>
    <div class="tour-card-description">
      <%# if tour.duration.present? %>
        <%#= t 'tours.card_duration.html', value: distance_of_time_in_words(tour.duration) %>
        <br>
      <%# end %>
      <%# if tour.distance.present? %>
        <%#= t 'tours.card_distance.html', value: number_to_human(tour.distance) %>
      <% end %>
         <td><%= link_to 'Detalhes', tour %></td>
        <td><%= link_to 'Editar', edit_tour_path(tour) %></td>
        <td><%= link_to 'Deletar', tour, method: :delete, data: { confirm: 'Você tem certeza?' } %></td>
    </div>
</div>
  <% end %>

data/server_promo/app/views/tours/edit.html.erb
<h1>Editing Tour</h1>

<%= render 'form', tour: @tour %>

<%= link_to 'Show', @tour %> |
<%= link_to 'Back', tours_path %>

data/server_promo/app/views/tours/index.html.erb
<p id="notice"><%= notice %></p>
<nav class="breadcrumb">
  <%#= link_to t('welcome.index.title'), root_path %>
  <%#= link_to t('tours.index.title'), tours_path %>
</nav>

<main class="content color-tour">
  <div class="content-filler-lg">
  </div>

  <header class="content-header">
<%= image_tag '/images/front_end/icons/pin-tour.svg', class: 'content-header-icon' %>
    <h1 class="content-header-title">
    Roteiros
    </h1>
  </header>

  <div class="content-retreat">
    <div class="grid">
<%= render 'tours/tour_card' %> 
 <br>

<%= link_to 'New Tour', new_tour_path %>

      <%# @tours.each do |tour| %>
        <%#= render 'tour', tour: tour %>
      <%# end %>
    </div>
  </div>
</main>

data/server_promo/app/views/tours/new.html.erb
<%= render 'form', tour: @tour %>

<%= link_to 'Voltar', tours_path %>

data/server_promo/app/views/tours/show.html.erb
<style>
#map-canvas {
height: 400px !important;
}
</style>
<p id="notice"><%= notice %></p>


<main class="content color-tour">
  <%= content_tag :div, id: "map-canvas", data: { tours: @tour.to_json(methods: [:name]) } do -%>
  <% end -%>


  <header class="content-header">
    <%= image_tag '/images/front_end/icons/pin-tour.svg', class: 'content-header-icon' %>
    <h1 class="content-header-title">  <%= @tour.name %>
    </h1>
    <span>
<%= link_to 'Edit', edit_tour_path(@tour) %> |
<%= link_to 'Back', tours_path %>


</span>
  </header>
  <div class="content-tabs">
  
    <%# if @tour.duration.present? %>
      <div class="content-tabs-item">
        <span>
      <%= image_tag "/images/front_end/icons/clock-yellow.svg", class: "content-tabs-icon" %>
          <%#= t 'tours.tab_duration' %>Duração: <strong><%= @tour.duration %></strong>
        </span>
      </div>
    <%# end %>
    <%# if @tour.distance.present? %>
      <div class="content-tabs-item">
        <span>
          <%= image_tag "/images/front_end/icons/walking.svg", class: "content-tabs-icon" %>
          <%#= t 'tours.tab_distance' %>Distância: <strong><%= @tour.distance %>km</strong>
        </span>
      </div>
    <%# end %>
    <div class="content-tabs-item">
      <span>
        <%= image_tag "/images/front_end/icons/crowd.svg", class: "content-tabs-icon" %>
        <%#= t 'tours.tab_audience' %>Público: <strong><%= @tour.audience %></strong>
      </span>
    </div>
    <div class="content-tabs-item">
      <span>
        <%= image_tag "/images/front_end/icons/heart.svg", class: "content-tabs-icon" %>
        <%#= t 'tours.tab_intensity' %>Dificuldade: <strong><%= @tour.intensity %></strong>
      </span>
    </div>
    <div class="content-tabs-spacer">
    </div>
    <div class="content-tabs-options">
      <%#= link_to "https://www.google.com.br/maps/dir/#{@tour.stops.map(&:place).map(&:coordinates).join('/')}", class: 'content-tabs-options-item', target: '_blank' do %>
        <%= image_tag '/images/front_end/directions.svg', class:'content-tabs-share-icon' %>
      <%# end %>
      <%#= link_to "https://www.facebook.com/sharer/sharer.php?u=#{tour_url(@tour)}", class: 'content-tabs-options-item', target: '_blank' do %>
        <%= image_tag '/images/front_end/facebook-white.svg', class:'content-tabs-share-icon' %>
      <%# end %>
      <%#= link_to "https://twitter.com/home?status=#{tour_url(@tour)}", class: 'content-tabs-options-item', target: '_blank' do %>
        <%= image_tag '/images/front_end/twitter-white.svg', class:'content-tabs-share-icon' %>
      <%# end %>
    </div>
  </div>

  <div class="content-frame">
  <img class="tour-detail-main-photo" src="<%= url_for(@tour.avatar.variant(resize: "800x600")) %>" alt="...">

    <section class="section">
      <h1 class="heading-one">Sobre o Roteiro:<%#= t 'tours.about_the_tour' %></h1>
      <p class="skip-4">
 <div class="weĺl">       
   <%= @tour.description %>
  </div>
  <hr>
       <%= sanitize @tour.details %>
      <%#= markdown_to_html @tour.description.to_s %>
      </p>
    </section>
<h1 class="heading-one">Neste Roteiro:<%#= t 'tours.about_the_tour' %></h1>

    <div style="display: flex; flex-wrap: wrap">
 <%= render 'pois/poicard', obj: @tour_pois %>
 </div>
   <%# @tour.stops.each_with_index do |stop, index| %>
      <%#= render 'stop', stop: stop, index: index + 1  %>
    <%# end %>
  </div>




<%= link_to 'Voltar', groups_path %>

</head>
<script id="jsbin-javascript">
// Generated by CoffeeScript 1.7.1
var GmapsWaypoints,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

GmapsWaypoints = (function() {
  function GmapsWaypoints(element, options) {
    var k;
    this.element = element;
    if (options == null) {
      options = {};
    }
    this.calcRoute = __bind(this.calcRoute, this);
    this.initialize = __bind(this.initialize, this);
    this.directionsService = new google.maps.DirectionsService();
    this.options = {
      latitude: -22.8976661,
      longitude: -47.0468233,
      travelMode: 'DRIVING',
      zoom: 13
      };
    for (k in options) {
      this.options[k] = options[k];
    }
  }

  GmapsWaypoints.prototype.initialize = function() {
    var centerMapLatLng, map, mapOptions;
    this.injectCssForMap();
    this.directionsDisplay = new google.maps.DirectionsRenderer();
    centerMapLatLng = new google.maps.LatLng(this.options.latitude, this.options.longitude);
    mapOptions = {
      zoom: this.options.zoom,
      center: centerMapLatLng
    };
    map = new google.maps.Map(this.element, mapOptions);
    return this.directionsDisplay.setMap(map);
  };

  GmapsWaypoints.prototype.injectCssForMap = function() {
    return $(this.element).css('width', '100%').css('height', '100%');
  };

  GmapsWaypoints.prototype.calcRoute = function(origin, locations, destination) {
    var i, request, waypts;
    waypts = [];
    i = 0;
    while (i < locations.length) {
      waypts.push({
        location: this.prepareLocation(locations[i]),
        stopover: true
      });
      i++;
    }
    request = {
      origin: new google.maps.LatLng(origin.latitude, origin.longitude),
      destination: new google.maps.LatLng(destination.latitude, destination.longitude),
      waypoints: waypts,
      optimizeWaypoints: true,
      travelMode: this.options.travelMode
    };
    return this.directionsService.route(request, (function(_this) {
      return function(response, status) {
        if (status === google.maps.DirectionsStatus.OK) {
          return _this.directionsDisplay.setDirections(response);
        }
      };
    })(this));
  };

  GmapsWaypoints.prototype.prepareLocation = function(loc) {
    if (typeof loc === 'string') {
      return loc;
    } else {
      return "" + loc.latitude + ", " + loc.longitude;
    }
  };

  return GmapsWaypoints;

})();


var gm = new GmapsWaypoints(document.getElementById('map-canvas'), {latitude: -22.8976661, longitude: -47.0468233});
    google.maps.event.addDomListener(window, "load", gm.initialize);

(function($){

    $(window).load(function(){
    gm.calcRoute(
                         {latitude: -22.8976661, longitude: -47.0468233},
                [
          <% @tour_pois.each do |poi| %>

                    {latitude: <%= poi.latitude %>, longitude: <%= poi.longitude %>},

                    <% end %>
                ],
                 {latitude: -22.8976661, longitude: -47.0468233}
            );
 });

 })(jQuery);
</script>
</div>
</div>
</main>